export interface ElementCustomization {
  id: string;
  name: string;
  category: 'header' | 'avatar' | 'status' | 'waveform' | 'actions' | 'mic' | 'button';
  x: number; // horizontal offset in px or %
  y: number; // vertical offset in px or %
  scale: number; // 0.4 to 3.0
  width?: number | string; // 'auto' or custom
  height?: number | string; // 'auto' or custom
  opacity: number; // 0 to 1
  borderRadius?: number; // px
  rotation: number; // degrees -180 to 180
  visible: boolean;
  customIcon?: string | null; // Lucide icon name or emoji
  customImage?: string | null; // Data URL or image path
  customText?: string | null; // Custom label override
  padding?: number; // px
  margin?: number; // px
}

export type LayoutCustomizationMap = Record<string, ElementCustomization>;

export const DEFAULT_ELEMENT_CUSTOMIZATIONS: LayoutCustomizationMap = {
  header_bar: {
    id: 'header_bar',
    name: 'Top Header Bar',
    category: 'header',
    x: 0,
    y: 0,
    scale: 1,
    opacity: 1,
    borderRadius: 0,
    rotation: 0,
    visible: true,
  },
  mithila_logo: {
    id: 'mithila_logo',
    name: 'Mithila Academy Logo & Title',
    category: 'header',
    x: 0,
    y: 0,
    scale: 1,
    opacity: 1,
    borderRadius: 16,
    rotation: 0,
    visible: true,
  },
  ai_teacher_live_badge: {
    id: 'ai_teacher_live_badge',
    name: 'AI Teacher Live Badge',
    category: 'header',
    x: 0,
    y: 0,
    scale: 1,
    opacity: 1,
    borderRadius: 999,
    rotation: 0,
    visible: true,
  },
  python_embed_btn: {
    id: 'python_embed_btn',
    name: 'Python Embed (.py) Button',
    category: 'header',
    x: 0,
    y: 0,
    scale: 1,
    opacity: 1,
    borderRadius: 12,
    rotation: 0,
    visible: true,
  },
  drive_btn: {
    id: 'drive_btn',
    name: 'Google Drive Button',
    category: 'header',
    x: 0,
    y: 0,
    scale: 1,
    opacity: 1,
    borderRadius: 12,
    rotation: 0,
    visible: true,
  },
  apk_btn: {
    id: 'apk_btn',
    name: 'Android APK App Button',
    category: 'header',
    x: 0,
    y: 0,
    scale: 1,
    opacity: 1,
    borderRadius: 12,
    rotation: 0,
    visible: true,
  },
  info_btn: {
    id: 'info_btn',
    name: 'Help & Info Button',
    category: 'header',
    x: 0,
    y: 0,
    scale: 1,
    opacity: 1,
    borderRadius: 12,
    rotation: 0,
    visible: true,
  },
  teacher_avatar: {
    id: 'teacher_avatar',
    name: 'AI Teacher Photo & Avatar',
    category: 'avatar',
    x: 0,
    y: 0,
    scale: 1,
    opacity: 1,
    borderRadius: 0,
    rotation: 0,
    visible: true,
  },
  status_card: {
    id: 'status_card',
    name: 'AI Teacher Status Card',
    category: 'status',
    x: 0,
    y: 0,
    scale: 1,
    opacity: 1,
    borderRadius: 16,
    rotation: 0,
    visible: true,
  },
  status_title: {
    id: 'status_title',
    name: 'AI Teacher Title Label',
    category: 'status',
    x: 0,
    y: 0,
    scale: 1,
    opacity: 1,
    borderRadius: 0,
    rotation: 0,
    visible: true,
  },
  status_pill: {
    id: 'status_pill',
    name: 'AI Teacher • Live Pill',
    category: 'status',
    x: 0,
    y: 0,
    scale: 1,
    opacity: 1,
    borderRadius: 6,
    rotation: 0,
    visible: true,
  },
  status_desc: {
    id: 'status_desc',
    name: 'Voice Status Description',
    category: 'status',
    x: 0,
    y: 0,
    scale: 1,
    opacity: 1,
    borderRadius: 0,
    rotation: 0,
    visible: true,
  },
  waveform_visualizer: {
    id: 'waveform_visualizer',
    name: 'Audio Waveform Equalizer',
    category: 'waveform',
    x: 0,
    y: 0,
    scale: 1,
    opacity: 1,
    borderRadius: 0,
    rotation: 0,
    visible: true,
  },
  quick_actions_bar: {
    id: 'quick_actions_bar',
    name: 'Quick Action Pills Container',
    category: 'actions',
    x: 0,
    y: 0,
    scale: 1,
    opacity: 1,
    borderRadius: 0,
    rotation: 0,
    visible: true,
  },
  action_btn_0: {
    id: 'action_btn_0',
    name: 'Explain Physics Pill',
    category: 'actions',
    x: 0,
    y: 0,
    scale: 1,
    opacity: 1,
    borderRadius: 999,
    rotation: 0,
    visible: true,
    customIcon: 'Atom',
  },
  action_btn_1: {
    id: 'action_btn_1',
    name: 'Open YouTube Pill',
    category: 'actions',
    x: 0,
    y: 0,
    scale: 1,
    opacity: 1,
    borderRadius: 999,
    rotation: 0,
    visible: true,
    customIcon: 'Youtube',
  },
  action_btn_2: {
    id: 'action_btn_2',
    name: 'Open WhatsApp Pill',
    category: 'actions',
    x: 0,
    y: 0,
    scale: 1,
    opacity: 1,
    borderRadius: 999,
    rotation: 0,
    visible: true,
    customIcon: 'MessageCircle',
  },
  action_btn_3: {
    id: 'action_btn_3',
    name: 'Give me a lesson Pill',
    category: 'actions',
    x: 0,
    y: 0,
    scale: 1,
    opacity: 1,
    borderRadius: 999,
    rotation: 0,
    visible: true,
    customIcon: 'Sparkles',
  },
  mic_button: {
    id: 'mic_button',
    name: 'Live Voice Microphone Button',
    category: 'mic',
    x: 0,
    y: 0,
    scale: 1,
    opacity: 1,
    borderRadius: 999,
    rotation: 0,
    visible: true,
  },
  mic_button_label: {
    id: 'mic_button_label',
    name: 'Mic Subtitle & Status Text',
    category: 'mic',
    x: 0,
    y: 0,
    scale: 1,
    opacity: 1,
    borderRadius: 0,
    rotation: 0,
    visible: true,
  },
};
